### ISSUE TITLE
Error during convertion custom LSTM model to edge model 

### ISSUE THREAD

**Issue by MaxRondelli** [google-ai-edge/ai-edge-torch#145]
### Description of the bug:

Hi there,

I am trying to convert my LSTM custom model with the library to put it on M5Stack ESP32 device. 
I occur in an error during the conversion though. I share my code.
```python
import torch
import config as cfg
import ai_edge_torch
from model import LSTMModel

BEST_MODEL = '/results/run_20240808_120746/models/best.pth'
INPUT_SIZE = cfg.n_input
HIDDEN_SIZE = cfg.n_hidden
NUM_LAYERS = cfg.n_layers
NUM_CLASSES = cfg.n_classes

model = LSTMModel(INPUT_SIZE, HIDDEN_SIZE, NUM_LAYERS, NUM_CLASSES)
dummy_input = (torch.randn(2, NUM_LAYERS, 9),)

edge_model = ai_edge_torch.convert(model.eval(), dummy_input)
edge_model.export("edge_model.tflite")
```

My `LSTMModel` class in my model folder is as follows:

```python
class LSTMModel(nn.Module):
    def __init__(self, n_input=n_input, n_hidden=n_hidden, n_layers=n_layers,
                 n_classes=n_classes, drop_prob=drop_prob):
        super(LSTMModel, self).__init__()

        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.n_classes = n_classes
        self.drop_prob = drop_prob
        self.n_input = n_input

        self.lstm1 = nn.LSTM(n_input, n_hidden, n_layers, dropout=self.drop_prob)
        self.lstm2 = nn.LSTM(n_hidden, n_hidden, n_layers, dropout=self.drop_prob)
        self.fc = nn.Linear(n_hidden, n_classes)
        self.dropout = nn.Dropout(drop_prob)

    def forward(self, x, hidden=None):
        # Initialize hidden state if not provided
        if hidden is None:
            h_0 = torch.zeros(self.n_layers, x.size(1), self.n_hidden).to(x.device)
            c_0 = torch.zeros(self.n_layers, x.size(1), self.n_hidden).to(x.device)
            hidden = (h_0, c_0)

        x = x.permute(1, 0, 2)  # Permute for the LSTM

        # First LSTM layer
        x, hidden1 = self.lstm1(x, hidden)

        # Additional LSTM layers (if any)
        for i in range(n_highway_layers):  # n_highway_layers should be defined in your class or passed to it
            x, hidden2 = self.lstm2(x, hidden)

        x = self.dropout(x)
        out = x[-1]
        out = out.contiguous().view(-1, self.n_hidden)
        out = self.fc(out)
        out = F.log_softmax(out, dim=1)

        return out

    def init_hidden(self, batch_size):
        ''' Initialize hidden state'''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        if (torch.cuda.is_available() ):
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
                weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                weight.new(self.n_layers, batch_size, self.n_hidden).zero_())

        return hidden
```
        

### Actual vs expected behavior:

```bash
2024-08-10 17:37:33.875015: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:root:PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING:root:Found CUDA without GPU_NUM_DEVICES. Defaulting to PJRT_DEVICE=CUDA with GPU_NUM_DEVICES=1
Traceback (most recent call last):
  File "/home/massimorondelli/Human-Activity-Recognition-with-Recurrent-Neural-Networks-on-IoT-Device/pytorch2onnx.py", line 58, in <module>
    edge_model = ai_edge_torch.convert(model.eval(), dummy_input)
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/ai_edge_torch/convert/converter.py", line 195, in convert
    return Converter().convert(
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/ai_edge_torch/convert/converter.py", line 134, in convert
    return conversion.convert_signatures(
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/ai_edge_torch/convert/conversion.py", line 97, in convert_signatures
    shlo_bundles: list[stablehlo.StableHLOModelBundle] = [
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/ai_edge_torch/convert/conversion.py", line 98, in <listcomp>
    cutils.exported_program_to_stablehlo_bundle(exported, sig.flat_args)
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/ai_edge_torch/convert/conversion_utils.py", line 133, in exported_program_to_stablehlo_bundle
    return stablehlo.exported_program_to_stablehlo(
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/torch_xla/stablehlo.py", line 618, in exported_program_to_stablehlo
    bundle = _exported_program_to_stablehlo_bundle(exported_model, options)
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/torch_xla/stablehlo.py", line 333, in _exported_program_to_stablehlo_bundle
    device = xm.xla_device()
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 212, in xla_device
    return runtime.xla_device(n, devkind)
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/torch_xla/runtime.py", line 95, in wrapper
    return fn(*args, **kwargs)
  File "/home/massimorondelli/miniconda3/envs/har/lib/python3.10/site-packages/torch_xla/runtime.py", line 124, in xla_device
    return torch.device(torch_xla._XLAC._xla_get_default_device())
RuntimeError: torch_xla/csrc/runtime/pjrt_registry.cc:213 : Check failed: client 
*** Begin stack trace ***
        tsl::CurrentStackTrace()
        torch_xla::runtime::InitializePjRt(std::string const&)
        torch_xla::runtime::PjRtComputationClient::PjRtComputationClient()

        torch_xla::runtime::GetComputationClient()
        torch_xla::bridge::GetDefaultDevice()
        torch_xla::bridge::GetCurrentDevice()
        torch_xla::bridge::GetCurrentAtenDevice()



        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault

        PyEval_EvalCode

        _PyRun_SimpleFileObject
        _PyRun_AnyFileObject
        Py_RunMain
        Py_BytesMain

        __libc_start_main

*** End stack trace ***
Unknown PJRT_DEVICE 'CUDA'
```

## Some useful version
- Python version: Python 3.10.14
- Torch version: 2.4.0
- Torch-xla version: 2.4.0
- Ai-edge-torch version: 0.2.0
- tensorflow-cpu: 2.17.0
- tensorflow-estimator: 2.15.0

**Comment by MaxRondelli** [comment]
I have solved the issue adding the line `os.environ['PJRT_DEVICE'] = 'CPU'`. It sets the prjt_device since it was unknown. 

```python
import os 
import torch
import ai_edge_torch
import config as cfg
from model import LSTMModel

os.environ['PJRT_DEVICE'] = 'CPU'

BEST_MODEL = '/results/run_20240808_120746/models/best.pth'
INPUT_SIZE = cfg.n_input
HIDDEN_SIZE = cfg.n_hidden
NUM_LAYERS = cfg.n_layers
NUM_CLASSES = cfg.n_classes

model = LSTMModel(INPUT_SIZE, HIDDEN_SIZE, NUM_LAYERS, NUM_CLASSES)
dummy_input = (torch.randn(2, NUM_LAYERS, 9),)

edge_model = ai_edge_torch.convert(model.eval(), dummy_input)
edge_model.export("edge_model.tflite")
```

**Comment by fdchiu** [comment]
I am having the same issue but the posted solution does not apply to my case: my model was trained and saved with GPU parameters. setting:
os.environ['PJRT_DEVICE'] = 'CPU'
the conversion process will crash with illegal instruction error.
I suspect ai_edge_torch is setting CPU devices only, so any torch model saved with gpu parameters will get a error:
Unknown PJRT_DEVICE 'CUDA'
