### ISSUE TITLE
YOLO-NAS Conversion Flow

### ISSUE THREAD

**Issue by Illia-tsar** [google-ai-edge/ai-edge-torch#169]
### Description of the bug:

When attempting to convert a YOLO-NAS neural network to TFLite using the `ai_edge_torch library`, the standard conversion flow works without issues. However, errors arise during quantization with PyTorch 2.0 Edge (PT2E). While I successfully handled quantization-level issues and produced a quantized model using `convert_pt2e`, calling `ai_edge_torch.convert` results in the following error:
"ConverterError: Variable constant folding is failed. Please consider using enabling `experimental_enable_resource_variables` flag in the TFLite converter object. For example, converter.experimental_enable_resource_variables = True."
I attempted to resolve this by passing the `experimental_enable_resource_variables` parameter through `_ai_edge_converter_flags` as follows: `{'experimental_enable_resource_variables': True}`, but it did not resolve the issue.

### Actual vs expected behavior:

The model should convert successfully with the applied quantization, so that I end up having a fully int8 TFLite. The conversion fails with a `ConverterError`, suggesting an issue with variable constant folding and the `experimental_enable_resource_variables` flag.

### Any other information you'd like to share?

YOLO-NAS supports PTQ and QAT out-of-the-box. I would like to know if it's compatible with `ai_edge_torch.convert`, and if not, how to make it compatible to leverage a built-in quantization mechanisms.

**Comment by pkgoogle** [comment]
Hi @Illia-tsar, please see if these instructions help: https://github.com/google-ai-edge/ai-edge-torch/blob/main/docs/pytorch_converter/README.md#quantization . Let me know if that helps.

**Comment by WangFengtu1996** [comment]
* I have same error.
* I want to quantize TCN model by PT2E with `ai-edge-torch`.  My code is as follow
```
 from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
        from torch._export import capture_pre_autograd_graph
        import ai_edge_torch
        from ai_edge_torch.quantize.pt2e_quantizer import get_symmetric_quantization_config
        from ai_edge_torch.quantize.pt2e_quantizer import PT2EQuantizer
        from ai_edge_torch.quantize.quant_config import QuantConfig

        self._create_model()
        self.model.load_state_dict(torch.load(self.model_file.as_posix(), map_location=self.device)['model'])
        self.model.eval()

        pt2e_quantizer = PT2EQuantizer().set_global(
            get_symmetric_quantization_config(is_per_channel=True, is_dynamic=True)
        )

        sample_args = (torch.randn(self.size),)
        pt2e_torch_model = capture_pre_autograd_graph( self.model, sample_args)
        pt2e_torch_model = prepare_pt2e(pt2e_torch_model, pt2e_quantizer)

        # Run the prepared model with sample input data to ensure that internal observers are populated with correct values
        pt2e_torch_model(*sample_args)

        # Convert the prepared model to a quantized model
        pt2e_torch_model = convert_pt2e(pt2e_torch_model, fold_quantize=False)
        tfl_converter_flags = {'experimental_enable_resource_variables': True }
        # Convert to an ai_edge_torch model
        pt2e_drq_model = ai_edge_torch.convert(pt2e_torch_model, sample_args, quant_config=QuantConfig(pt2e_quantizer=pt2e_quantizer), _ai_edge_converter_flags=tfl_converter_flags)

        pt2e_drq_model.export((self.model_name.parent /  (self.model_name.stem + '.' +self.fmt)).as_posix())
```
My log is as floow 
```
2024-08-27 15:08:46.515273: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-27 15:08:46.522259: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1724742526.529978 2280809 cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1724742526.532323 2280809 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-27 15:08:46.538093: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-27 15:08:46.942846: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
/home/wangft/workspace/weigh/train_model/tasks/task.py:327: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model.load_state_dict(torch.load(self.model_file.as_posix(), map_location=self.device)['model'])
W0827 15:08:49.425000 128804724126784 torch/_export/__init__.py:95] +============================+
W0827 15:08:49.425000 128804724126784 torch/_export/__init__.py:96] |     !!!   WARNING   !!!    |
W0827 15:08:49.425000 128804724126784 torch/_export/__init__.py:97] +============================+
W0827 15:08:49.425000 128804724126784 torch/_export/__init__.py:98] capture_pre_autograd_graph() is deprecated and doesn't provide any function guarantee moving forward.
W0827 15:08:49.425000 128804724126784 torch/_export/__init__.py:99] Please switch to use torch.export instead.
2024-08-27 15:08:53,377 - WARNING - conversion.py:69 - Your model is converted in training mode. Please set the module in evaluation mode with `module.eval()` for better on-device performance and compatibility.
/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: At pre-dispatch tracing, we will assume that any custom op that is marked with CompositeImplicitAutograd and functional are safe to not decompose. We found quantized_decomposed.quantize_per_channel.default to be one such op.
  warnings.warn(
/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: At pre-dispatch tracing, we will assume that any custom op that is marked with CompositeImplicitAutograd and functional are safe to not decompose. We found quantized_decomposed.dequantize_per_channel.default to be one such op.
  warnings.warn(
2024-08-27 15:08:56,867 - WARNING - runtime.py:42 - PJRT is now the default runtime. For more information, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
2024-08-27 15:08:56,868 - WARNING - runtime.py:59 - Defaulting to PJRT_DEVICE=CPU
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1724742536.870338 2280809 cpu_client.cc:467] TfrtCpuClient created.
I0000 00:00:1724742536.931752 2280809 cuda_executor.cc:809] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
W0000 00:00:1724742536.948024 2280809 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-08-27 15:08:57,317 - INFO - signature_serialization.py:156 - Function `inner` contains input name(s) resource with unsupported characters which will be renamed to xlacallmodule_readvariableop_105_resource in the SavedModel.
INFO:tensorflow:Assets written to: /tmp/tmpl5lxb7ma/assets
2024-08-27 15:08:57,702 - INFO - builder_impl.py:836 - Assets written to: /tmp/tmpl5lxb7ma/assets
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1724742538.033371 2280809 tf_tfl_flatbuffer_helpers.cc:361] Ignored output_format.
W0000 00:00:1724742538.033389 2280809 tf_tfl_flatbuffer_helpers.cc:364] Ignored drop_control_dependency.
2024-08-27 15:08:58.033672: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tmpl5lxb7ma
2024-08-27 15:08:58.035159: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2024-08-27 15:08:58.035168: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: /tmp/tmpl5lxb7ma
I0000 00:00:1724742538.047750 2280809 mlir_graph_optimization_pass.cc:401] MLIR V1 optimization pass is not enabled
2024-08-27 15:08:58.049375: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2024-08-27 15:08:58.138205: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: /tmp/tmpl5lxb7ma
2024-08-27 15:08:58.157440: I tensorflow/cc/saved_model/loader.cc:462] SavedModel load for tags { serve }; Status: success: OK. Took 123770 microseconds.
2024-08-27 15:08:58.175404: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite(callsite("torch.fx.graph_module.GraphModule.__new__.<locals>.GraphModuleImpl/models.tcnn.TCNN_Block_net/torch.nn.modules.container.Sequential_network/models.tcnn.ResBlock_0/torch.nn.modules.container.Sequential_TCM_net/models.tcnn.DepthwiseSeparableConv_3/torch.nn.modules.container.Sequential_net/torch.nn.modules.conv.Conv1d_0;" at fused["XlaCallModule:", "XlaCallModule@__inference_inner_685"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_903"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tfl.transpose' op has mismatched quantized axes of input and output
Traceback (most recent call last):
  File "/home/wangft/workspace/weigh/train_model/export3.py", line 7, in <module>
    task.run3()
  File "/home/wangft/workspace/weigh/train_model/tasks/task.py", line 345, in run3
    pt2e_drq_model = ai_edge_torch.convert(pt2e_torch_model, sample_args, quant_config=QuantConfig(pt2e_quantizer=pt2e_quantizer), _ai_edge_converter_flags=tfl_converter_flags)
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/ai_edge_torch/_convert/converter.py", line 241, in convert
    return Converter().convert(
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/ai_edge_torch/_convert/converter.py", line 163, in convert
    return conversion.convert_signatures(
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/ai_edge_torch/_convert/conversion.py", line 104, in convert_signatures
    tflite_model = lowertools.exported_programs_to_tflite(
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/ai_edge_torch/lowertools/_shim.py", line 75, in exported_programs_to_tflite
    return utils.merged_bundle_to_tfl_model(
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/ai_edge_torch/lowertools/torch_xla_utils.py", line 262, in merged_bundle_to_tfl_model
    tflite_model = converter.convert()
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1231, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1183, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1562, in convert
    return self._convert_from_saved_model(graph_def)
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/lite.py", line 1423, in _convert_from_saved_model
    result = _convert_saved_model(**converter_kwargs)
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 1031, in convert_saved_model
    data = convert(
  File "/home/wangft/anaconda3/envs/py310/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 376, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: Variable constant folding is failed. Please consider using enabling `experimental_enable_resource_variables` flag in the TFLite converter object. For example, converter.experimental_enable_resource_variables = True<unknown>:0: error: loc(callsite(callsite(callsite("torch.fx.graph_module.GraphModule.__new__.<locals>.GraphModuleImpl/models.tcnn.TCNN_Block_net/torch.nn.modules.container.Sequential_network/models.tcnn.ResBlock_0/torch.nn.modules.container.Sequential_TCM_net/models.tcnn.DepthwiseSeparableConv_3/torch.nn.modules.container.Sequential_net/torch.nn.modules.conv.Conv1d_0;" at fused["XlaCallModule:", "XlaCallModule@__inference_inner_685"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_903"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tfl.transpose' op has mismatched quantized axes of input and output
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from

```

environment
```
ai-edge-quantizer-nightly    0.0.1.dev20240718
ai-edge-torch-nightly        0.3.0.dev20240817
torch                        2.4.0+cpu
torch-xla                    2.4.0
torchaudio                   2.4.0+cpu
```
