### ISSUE TITLE
Unable to resolve runtime symbol: `xla_mark_tensor'.

### ISSUE THREAD

**Issue by Clod98** [google-ai-edge/ai-edge-torch#265]
### Description of the bug:

I'm trying to convert a MobileNetV4 pytorch model to tflite. I get an error regarding the torch_xla library.

### Actual vs expected behavior:

What I get is: 

```
E0000 00:00:1727451183.700072  140566 simple_orc_jit.cc:433] Unable to resolve runtime symbol: `xla_mark_tensor'. Hint: if the symbol a custom call target, make sure you've registered it with the JIT using XLA_CPU_REGISTER_CUSTOM_CALL_TARGET.
JIT session error: Symbols not found: [ xla_mark_tensor ]
Traceback (most recent call last):
  File "/home/claudiu/workspaces/midas-depth-estimation/export.py", line 305, in <module>
    main()
  File "/home/claudiu/workspaces/midas-depth-estimation/export.py", line 299, in main
    export_ai_edge(model, input_size, output)
  File "/home/claudiu/workspaces/midas-depth-estimation/export.py", line 139, in export_ai_edge
    edge_model = ai_edge_torch.convert(model, img)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/ai_edge_torch/_convert/converter.py", line 241, in convert
    return Converter().convert(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/ai_edge_torch/_convert/converter.py", line 163, in convert
    return conversion.convert_signatures(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/ai_edge_torch/_convert/conversion.py", line 105, in convert_signatures
    tflite_model = lowertools.exported_programs_to_tflite(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/ai_edge_torch/lowertools/_shim.py", line 66, in exported_programs_to_tflite
    bundles: list[utils.MlirBundle] = [
                                      ^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/ai_edge_torch/lowertools/_shim.py", line 67, in <listcomp>
    utils.exported_program_to_mlir(exported, sig.flat_args)
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/ai_edge_torch/lowertools/torch_xla_utils.py", line 65, in exported_program_to_mlir
    return stablehlo.exported_program_to_stablehlo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 618, in exported_program_to_stablehlo
    bundle = _exported_program_to_stablehlo_bundle(exported_model, options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claudiu/miniconda3/envs/ai-edge-env/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 395, in _exported_program_to_stablehlo_bundle
    ) = torch_xla._XLAC._get_tensors_xla_device_data_node(res)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _get_tensors_xla_device_data_node(): incompatible function arguments. The following argument types are supported:
    1. (arg0: list[torch.Tensor]) -> tuple[list[int], list[IValue]]
```

### Any other information you'd like to share?

I already tried to change python version from 3.10 to 3.11. I also created the environment using the packages requested [here](https://raw.githubusercontent.com/google-ai-edge/ai-edge-torch/main/requirements.txt) . I've been using the nightly release (I didn't clone the repo yet). The import of the XLA library works correctly (after updating the LD_LIBRARY_PATH). I'm working on Ubuntu 22.04 and the model was trained on CPU.

**Comment by pkgoogle** [comment]
Hi @Clod98, do you have the actual conversion script which produces this error? Thanks.

**Comment by Clod98** [comment]
Thank you for replying.
I start by saying that the model we are using it's not one of the models already available in torchvision (I already tried converting a ResNet18 model and that's work just fine). I'm working with a Encoder-Decoder model based on MobileNetV4. Could it be related to this more complex architecture ?

**Comment by pkgoogle** [comment]
Hi @Clod98, definitely a possibility... is there a way to reduce the model to just a unique set of ops which may reproduce this issue (a dummy model if you will)? If you wish to reduce it further to protect your IP (like repeatedly bisecting it), and give us a more easily reproducible example that'll be even better for us.

**Comment by huronsw** [comment]
I've been pretty successful trying to convert torchvision models, but
I ran into this same error trying to convert some torchaudio models:

```
import ai_edge_torch
import torch
import torchaudio
from torchaudio.utils import download_asset

SPEECH_FILE = download_asset("tutorial-assets/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav")
device = torch.device("cpu")
bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
model = bundle.get_model().to(device)
waveform, sample_rate = torchaudio.load(SPEECH_FILE)
waveform = waveform.to(device)

if sample_rate != bundle.sample_rate:
    waveform = torchaudio.functional.resample(waveform, sample_rate, bundle.sample_rate)
sample_input = (waveform,)
edge_model = ai_edge_torch.convert(model, sample_input)
edge_model.export(f'wav2vec.tflite')
```

I'm also attempting to use the CPU runtime.

**Comment by pkgoogle** [comment]
I was able to replicate with some modifications for debugging:

```py
import ai_edge_torch
from ai_edge_torch.debug import find_culprits
import torch
import torchaudio
from torchaudio.utils import download_asset

SPEECH_FILE = download_asset("tutorial-assets/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav")
device = torch.device("cpu")
bundle = torchaudio.pipelines.WAV2VEC2_ASR_BASE_960H
model = bundle.get_model().to(device)
waveform, sample_rate = torchaudio.load(SPEECH_FILE)
waveform = waveform.to(device)

if sample_rate != bundle.sample_rate:
    waveform = torchaudio.functional.resample(waveform, sample_rate, bundle.sample_rate)
sample_input = (waveform,)
culprits = find_culprits(model, sample_input)
culprit = next(culprits)
culprit.print_code()
```

output:
```sh
2024-10-03 16:38:31.048024: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:3893] Estimated count of arithmetic ops: 46.668 G  ops, equivalently 23.334 G  MACs
E0000 00:00:1727973512.432769 1972461 simple_orc_jit.cc:433] Unable to resolve runtime symbol: `xla_mark_tensor'. Hint: if the symbol a custom call target, make sure you've registered it with the JIT using XLA_CPU_REGISTER_CUSTOM_CALL_TARGET.
JIT session error: Symbols not found: [ xla_mark_tensor ]
E0000 00:00:1727973513.186798 1972461 simple_orc_jit.cc:433] Unable to resolve runtime symbol: `xla_mark_tensor'. Hint: if the symbol a custom call target, make sure you've registered it with the JIT using XLA_CPU_REGISTER_CUSTOM_CALL_TARGET.
JIT session error: Symbols not found: [ xla_mark_tensor ]
W0000 00:00:1727973514.478792 1972461 tf_tfl_flatbuffer_helpers.cc:365] Ignored output_format.
W0000 00:00:1727973514.478824 1972461 tf_tfl_flatbuffer_helpers.cc:368] Ignored drop_control_dependency.
2024-10-03 16:38:34.479108: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tmpoq0atj8d
2024-10-03 16:38:34.479391: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2024-10-03 16:38:34.479414: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: /tmp/tmpoq0atj8d
2024-10-03 16:38:34.480417: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2024-10-03 16:38:34.484410: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: /tmp/tmpoq0atj8d
2024-10-03 16:38:34.487140: I tensorflow/cc/saved_model/loader.cc:466] SavedModel load for tags { serve }; Status: success: OK. Took 8036 microseconds.
2024-10-03 16:38:34.518379: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:3893] Estimated count of arithmetic ops: 0  ops, equivalently 0  MACs
W0000 00:00:1727973516.096475 1972461 tf_tfl_flatbuffer_helpers.cc:365] Ignored output_format.
W0000 00:00:1727973516.096515 1972461 tf_tfl_flatbuffer_helpers.cc:368] Ignored drop_control_dependency.
2024-10-03 16:38:36.096805: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tmpdlil5cb9
2024-10-03 16:38:36.097123: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2024-10-03 16:38:36.097146: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: /tmp/tmpdlil5cb9
2024-10-03 16:38:36.098379: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2024-10-03 16:38:36.102408: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: /tmp/tmpdlil5cb9
2024-10-03 16:38:36.105220: I tensorflow/cc/saved_model/loader.cc:466] SavedModel load for tags { serve }; Status: success: OK. Took 8420 microseconds.
2024-10-03 16:38:36.136724: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:3893] Estimated count of arithmetic ops: 797.702 M  ops, equivalently 398.851 M  MACs
import torch
from torch import device
import ai_edge_torch

class CulpritGraphModule(torch.nn.Module):
    def forward(self, arg0_1: "f32[29, 768]", arg1_1: "f32[29]", arg2_1: "f32[1, 169, 768]"):
        # File: /xxxxxxxxx/git/ai-edge-torch/venv/lib/python3.11/site-packages/torchaudio/models/wav2vec2/model.py:119 in forward, code: x = self.aux(x)
        view: "f32[169, 768]" = torch.ops.aten.view.default(arg2_1, [169, 768]);  arg2_1 = None
        t: "f32[768, 29]" = torch.ops.aten.t.default(arg0_1);  arg0_1 = None
        addmm: "f32[169, 29]" = torch.ops.aten.addmm.default(arg1_1, view, t);  arg1_1 = view = t = None
        view_1: "f32[1, 169, 29]" = torch.ops.aten.view.default(addmm, [1, 169, 29]);  addmm = None
        return (view_1, None)

_args = (
    torch.randn((29, 768,), dtype=torch.float32),
    torch.randn((29,), dtype=torch.float32),
    torch.randn((1, 169, 768,), dtype=torch.float32),
)

_edge_model = ai_edge_torch.convert(CulpritGraphModule().eval(), _args)

I0000 00:00:1727973519.979383 1972461 cpu_client.cc:470] TfrtCpuClient destroyed.
```
