### ISSUE TITLE
Error while converting gemma2-2b 

### ISSUE THREAD

**Issue by Harshbande05** [google-ai-edge/ai-edge-torch#315]
### Description of the bug:

Traceback (most recent call last):
  File "/home/Google/ai-edge-torch/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py", line 68, in <module>
    app.run(main)
  File "/home/Google/venv/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/Google/venv/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/Google/ai-edge-torch/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py", line 54, in main
    pytorch_model = gemma2.build_2b_model(
  File "/home/Google/ai-edge-torch/ai_edge_torch/generative/examples/gemma/gemma2.py", line 258, in build_2b_model
    loader.load(model, strict=False)
  File "/home/Google/ai-edge-torch/ai_edge_torch/generative/utilities/loader.py", line 157, in load
    converted_state["tok_embedding.weight"] = state.pop(
KeyError: 'embedder.weight'

**OPEN TO SUGGETIONS**

**Comment by pkgoogle** [comment]
Hi @Harshbande05 I got a different but similar error using the latest code on main, commit; 4ecdbee1c55c2cb6e551e746e6ee1c43149c1b0e:

my output:
```sh
$ python convert_gemma2_to_tflite.py
...
Traceback (most recent call last):
  File "/xxxxxx/git/ai-edge-torch/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py", line 68, in <module>
    app.run(main)
  File "/xxxxxx/envs/aet_head/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/xxxxxx/envs/aet_head/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/xxxxxx/git/ai-edge-torch/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py", line 54, in main
    pytorch_model = gemma2.build_2b_model(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxxx/git/ai-edge-torch/ai_edge_torch/generative/examples/gemma/gemma2.py", line 258, in build_2b_model
    loader.load(model, strict=False)
  File "/xxxxxx/git/ai-edge-torch/ai_edge_torch/generative/utilities/loader.py", line 153, in load
    state = self._loader(self._file_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxxx/git/ai-edge-torch/ai_edge_torch/generative/utilities/loader.py", line 84, in load_pytorch_statedict
    this_file_tensors = torch.load(file)
                        ^^^^^^^^^^^^^^^^
  File "/xxxxxx/envs/aet_head/lib/python3.11/site-packages/torch/serialization.py", line 1384, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/xxxxxx/envs/aet_head/lib/python3.11/site-packages/torch/serialization.py", line 1628, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by haozha111** [comment]
qq: are you using the checkpoint from kaggle? Gemma-2-2b-it:
https://www.kaggle.com/models/google/gemma-2

**Comment by pkgoogle** [comment]
I was able to convert w/ the Kaggle checkpoint (was previously using the HF one)... it takes a decent amount of time depending on your setup >5 minutes. @Harshbande05, can you try with the Kaggle checkpoint?

kaggle checkpoint d/ling:
```py
import kagglehub

# Download latest version
path = kagglehub.model_download("google/gemma-2/pyTorch/gemma-2-2b-it")

print("Path to model files:", path)
```

I tested on the same commit.
