### ISSUE TITLE
nn.BatchNorm2d with affine=False

### ISSUE THREAD

**Issue by shubhamgupto** [google-ai-edge/ai-edge-torch#317]
### Description of the bug:

unsupported operand type(s) for *: 'FunctionalTensor' and 'NoneType'

While executing %_native_batch_norm_legit_no_training : [num_users=1] = call_function[target=ai_edge_torch.convert.fx_passes.optimize_layout_transposes_pass.layout_rewrite.batch_norm](args = (%convolution, None, None, %b_getattr_l__self___block1___0___layer_1_running_mean, %b_getattr_l__self___block1___0___layer_1_running_var, 0.1, 1e-05), kwargs = {})
Original traceback:
  File "/mnt/c/Users/shubh/Documents/workspace/xfeat-port-dlc/src/accelerated_features/modules/model.py", line 203, in forward
    x1 = self.block1(x)
  File "/mnt/c/Users/shubh/Documents/workspace/xfeat-port-dlc/src/accelerated_features/modules/model.py", line 77, in forward
    return self.layer(x)
    
```
class BasicLayer(nn.Module):
	"""
	  Basic Convolutional Layer: Conv2d -> BatchNorm -> ReLU
	"""
	def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, dilation=1, bias=False):
		super().__init__()
		self.layer = nn.Sequential(
				nn.Conv2d( in_channels, out_channels, kernel_size, padding = padding, stride=stride, dilation=dilation, bias = bias),
				nn.BatchNorm2d(out_channels, affine=False),
			#   CustomBatchNorm2d(out_channels, affine=False),  # Replace with custom batch norm
				nn.ReLU(inplace = True),
			)

	def forward(self, x):
	  return self.layer(x)
```

### Actual vs expected behavior:

Fails to handle nn.BatchNorm2d with affine=False

### Any other information you'd like to share?

complete source code - https://github.com/verlab/accelerated_features/blob/main/modules/xfeat.py

**Comment by pkgoogle** [comment]
Hi @shubhamgupto, I was able to convert successfully this way (with latest code `pip install -e .` in root directory):

```py
import torch
from torch import nn
import ai_edge_torch


class BasicLayer(nn.Module):
	"""
	  Basic Convolutional Layer: Conv2d -> BatchNorm -> ReLU
	"""
	def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, dilation=1, bias=False):
		super().__init__()
		self.layer = nn.Sequential(
				nn.Conv2d( in_channels, out_channels, kernel_size, padding = padding, stride=stride, dilation=dilation, bias = bias),
				nn.BatchNorm2d(out_channels, affine=False),
			#   CustomBatchNorm2d(out_channels, affine=False),  # Replace with custom batch norm
				nn.ReLU(inplace = True),
			)

	def forward(self, x):
	  return self.layer(x)


model = BasicLayer(3, 32)
sample_inputs = (torch.randn(1, 3, 224, 224),)

edge_model = ai_edge_torch.convert(model.eval(), sample_inputs)
edge_model.export("model.tflite")
```

**Comment by pkgoogle** [comment]
It's still working for me... so this means this is likely an environmental difference. The commit I updated and installed with is this one: 1c1dcb5c9a18f589e3c07af0ef899cb619e46ac7, can you try installing the code w/ this commit exactly?

I'm also using venv.

```sh
$ python --version
Python 3.11.9
```

My pip package environment, any obvious differences here? (focus on most relevant packages), can you also try with a fresh venv environment?:
```sh
$ pip list
Package                      Version             Editable project location
---------------------------- ------------------- ------------------------------------------------
absl-py                      2.1.0
ai-edge-litert-nightly       1.0.1.dev20241022
ai-edge-quantizer-nightly    0.0.1.dev20241022
ai-edge-torch                0.3.0               /xxxxxxxx/git/ai-edge-torch
astunparse                   1.6.3
certifi                      2024.8.30
charset-normalizer           3.4.0
click                        8.1.7
colored-traceback            0.4.2
contourpy                    1.3.0
cycler                       0.12.1
docker-pycreds               0.4.0
filelock                     3.16.1
flatbuffers                  24.3.25
fonttools                    4.54.1
fsspec                       2024.10.0
gast                         0.6.0
gitdb                        4.0.11
GitPython                    3.1.43
google-pasta                 0.2.0
grpcio                       1.67.0
h5py                         3.12.1
idna                         3.10
immutabledict                4.2.0
Jinja2                       3.1.4
joblib                       1.4.2
kagglehub                    0.3.3
keras-nightly                3.6.0.dev2024101603
kiwisolver                   1.4.7
libclang                     18.1.1
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   3.0.2
matplotlib                   3.9.2
mdurl                        0.1.2
ml-dtypes                    0.4.1
mpmath                       1.3.0
namex                        0.0.8
networkx                     3.4.2
numpy                        2.1.2
nvidia-cublas-cu12           12.4.5.8
nvidia-cuda-cupti-cu12       12.4.127
nvidia-cuda-nvrtc-cu12       12.4.127
nvidia-cuda-runtime-cu12     12.4.127
nvidia-cudnn-cu12            9.1.0.70
nvidia-cufft-cu12            11.2.1.3
nvidia-curand-cu12           10.3.5.147
nvidia-cusolver-cu12         11.6.1.9
nvidia-cusparse-cu12         12.3.1.170
nvidia-nccl-cu12             2.21.5
nvidia-nvjitlink-cu12        12.4.127
nvidia-nvtx-cu12             12.4.127
opt_einsum                   3.4.0
optree                       0.13.0
packaging                    24.1
pillow                       10.2.0
pip                          24.0
platformdirs                 4.3.6
protobuf                     5.28.2
psutil                       6.1.0
Pygments                     2.18.0
pyparsing                    3.2.0
python-dateutil              2.9.0.post0
PyYAML                       6.0.2
requests                     2.32.3
rich                         13.9.3
safetensors                  0.4.5
scikit-learn                 1.5.2
scipy                        1.14.1
sentry-sdk                   2.17.0
setproctitle                 1.3.3
setuptools                   70.3.0
six                          1.16.0
smmap                        5.0.1
sympy                        1.13.1
tabulate                     0.9.0
tb-nightly                   2.18.0a20240925
tensorboard-data-server      0.7.2
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.5.0
tf_nightly                   2.19.0.dev20241001
threadpoolctl                3.5.0
torch                        2.5.0
torch-xla                    2.5.0
torchaudio                   2.5.0+cpu
torchvision                  0.20.0+cpu
tqdm                         4.66.5
triton                       3.1.0
typing_extensions            4.12.2
urllib3                      2.2.3
wandb                        0.18.5
Werkzeug                     3.0.4
wheel                        0.44.0
wrapt                        1.16.0
```

**Comment by shubhamgupto** [comment]
Hey @pkgoogle thank you for the env, it kind of helped

heres after matching all the nightly build versions, heres a new error i got

```
python test.py
2024-10-30 13:20:39.268748: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-30 13:20:39.654170: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730308839.806235    5176 cuda_dnn.cc:8312] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730308839.851925    5176 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-30 13:20:40.343882: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:root:Found CUDA without GPU_NUM_DEVICES. Defaulting to PJRT_DEVICE=CUDA with GPU_NUM_DEVICES=1
E1030 13:20:54.295405    5176 cuda_dnn.cc:534] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E1030 13:20:54.295709    5176 cuda_dnn.cc:538] Memory usage: 958398464 bytes free, 8585216000 bytes total.
E1030 13:20:54.316324    5176 cuda_dnn.cc:534] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E1030 13:20:54.316644    5176 cuda_dnn.cc:538] Memory usage: 958398464 bytes free, 8585216000 bytes total.
Traceback (most recent call last):
  File "/mnt/c/Users/shubh/Documents/workspace/xfeat-port-dlc/src/accelerated_features/modules/test.py", line 26, in <module>
    edge_model = ai_edge_torch.convert(model.eval(), sample_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/shubh/Documents/workspace/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 254, in convert
    return Converter().convert(
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/shubh/Documents/workspace/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 169, in convert
    return conversion.convert_signatures(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/shubh/Documents/workspace/ai-edge-torch/ai_edge_torch/_convert/conversion.py", line 138, in convert_signatures
    tflite_model = lowertools.exported_programs_to_tflite(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/shubh/Documents/workspace/ai-edge-torch/ai_edge_torch/lowertools/_shim.py", line 66, in exported_programs_to_tflite
    bundles: list[utils.MlirBundle] = [
                                      ^
  File "/mnt/c/Users/shubh/Documents/workspace/ai-edge-torch/ai_edge_torch/lowertools/_shim.py", line 67, in <listcomp>
    utils.exported_program_to_mlir(exported, sig.flat_args)
  File "/mnt/c/Users/shubh/Documents/workspace/ai-edge-torch/ai_edge_torch/lowertools/torch_xla_utils.py", line 65, in exported_program_to_mlir
    return stablehlo.exported_program_to_stablehlo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/dav2/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 626, in exported_program_to_stablehlo
    bundle = _exported_program_to_stablehlo_bundle(exported_model, options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/dav2/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 349, in _exported_program_to_stablehlo_bundle
    xm.mark_step()
  File "/root/miniconda3/envs/dav2/lib/python3.11/site-packages/torch_xla/core/xla_model.py", line 1046, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: Bad StatusOr access: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

pip list
```
Package                        Version             Editable project location
------------------------------ ------------------- ----------------------------------------------------
absl-py                        2.1.0
ai-edge-litert                 1.0.1
ai-edge-litert-nightly         1.0.1.dev20241022
ai-edge-model-explorer         0.1.13
ai-edge-model-explorer-adapter 0.1.5
ai-edge-quantizer-nightly      0.0.1.dev20241022
ai-edge-torch                  0.3.0               xxxxxxxxxx/ai-edge-torch
aiohappyeyeballs               2.4.3
aiohttp                        3.10.10
aiosignal                      1.3.1
anyio                          4.6.2
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
asttokens                      2.0.5
astunparse                     1.6.3
async-lru                      2.0.4
attrs                          24.2.0
Babel                          2.11.0
beautifulsoup4                 4.12.3
bleach                         4.1.0
blinker                        1.8.2
Brotli                         1.0.9
cachetools                     5.5.0
certifi                        2024.8.30
cffi                           1.17.1
charset-normalizer             3.3.2
click                          8.1.7
cloud-tpu-client               0.10
coloredlogs                    15.0.1
comm                           0.2.1
contourpy                      1.3.0
cycler                         0.12.1
debugpy                        1.6.7
decorator                      5.1.1
defusedxml                     0.7.1
einops                         0.8.0
executing                      0.8.3
fastjsonschema                 2.16.2
filelock                       3.16.1
Flask                          3.0.3
flatbuffers                    24.3.25
fonttools                      4.54.1
frozenlist                     1.4.1
fsspec                         2024.9.0
gast                           0.6.0
google-api-core                1.34.1
google-api-python-client       1.8.0
google-auth                    2.35.0
google-auth-httplib2           0.2.0
google-pasta                   0.2.0
googleapis-common-protos       1.65.0
grpcio                         1.67.0
h11                            0.14.0
h5py                           3.12.1
httpcore                       1.0.2
httplib2                       0.22.0
httpx                          0.27.0
humanfriendly                  10.0
idna                           3.7
immutabledict                  4.2.0
iniconfig                      2.0.0
ipykernel                      6.29.5
ipython                        8.27.0
ipywidgets                     8.1.2
itsdangerous                   2.2.0
jedi                           0.19.1
Jinja2                         3.1.4
joblib                         1.4.2
json5                          0.9.6
jsonschema                     4.23.0
jsonschema-specifications      2023.7.1
jupyter                        1.0.0
jupyter_client                 8.6.0
jupyter-console                6.6.3
jupyter_core                   5.7.2
jupyter-events                 0.10.0
jupyter-lsp                    2.2.0
jupyter_server                 2.14.1
jupyter_server_terminals       0.4.4
jupyterlab                     4.2.5
jupyterlab-pygments            0.1.2
jupyterlab_server              2.27.3
jupyterlab-widgets             3.0.10
keras-nightly                  3.6.0.dev2024101603
kiwisolver                     1.4.7
kornia                         0.7.3
kornia_rs                      0.1.5
libclang                       18.1.1
lightning-utilities            0.11.8
loguru                         0.7.2
Markdown                       3.7
markdown-it-py                 3.0.0
MarkupSafe                     2.1.3
matplotlib                     3.9.2
matplotlib-inline              0.1.6
mdurl                          0.1.2
mistune                        2.0.4
ml-dtypes                      0.4.1
mpmath                         1.3.0
multidict                      6.1.0
namex                          0.0.8
nbclient                       0.8.0
nbconvert                      7.16.4
nbformat                       5.10.4
nest-asyncio                   1.6.0
networkx                       3.4.1
notebook                       7.2.2
notebook_shim                  0.2.3
numpy                          1.26.4
nvidia-cublas-cu12             12.4.5.8
nvidia-cuda-cupti-cu12         12.4.127
nvidia-cuda-nvrtc-cu12         12.4.127
nvidia-cuda-runtime-cu12       12.4.127
nvidia-cudnn-cu12              9.1.0.70
nvidia-cufft-cu12              11.2.1.3
nvidia-curand-cu12             10.3.5.147
nvidia-cusolver-cu12           11.6.1.9
nvidia-cusparse-cu12           12.3.1.170
nvidia-nccl-cu12               2.21.5
nvidia-nvjitlink-cu12          12.4.127
nvidia-nvtx-cu12               12.4.127
oauth2client                   4.1.3
onnx                           1.13.0
onnxruntime                    1.19.2
onnxruntime-gpu                1.19.2
onnxsim                        0.4.36
onnxslim                       0.1.35
opencv-python                  4.10.0.84
opt_einsum                     3.4.0
optree                         0.13.0
overrides                      7.4.0
packaging                      24.1
pandocfilters                  1.5.0
parso                          0.8.3
pexpect                        4.8.0
pillow                         11.0.0
pip                            24.2
platformdirs                   3.10.0
pluggy                         1.5.0
ply                            3.11
portpicker                     1.6.0
prometheus-client              0.14.1
prompt-toolkit                 3.0.43
propcache                      0.2.0
protobuf                       3.20.3
psutil                         5.9.0
ptyprocess                     0.7.0
pure-eval                      0.2.2
pyasn1                         0.6.1
pyasn1_modules                 0.4.1
pybind11                       2.13.6
pybind11_global                2.13.6
pycparser                      2.21
Pygments                       2.15.1
pyparsing                      3.2.0
PyQt5                          5.15.10
PyQt5-sip                      12.13.0
PySocks                        1.7.1
pytest                         8.3.3
python-dateutil                2.9.0.post0
python-json-logger             2.0.7
pytorch-lightning              2.4.0
pytz                           2024.1
PyYAML                         6.0.2
pyzmq                          25.1.2
qtconsole                      5.6.0
QtPy                           2.4.1
referencing                    0.30.2
requests                       2.32.3
rfc3339-validator              0.1.4
rfc3986-validator              0.1.1
rich                           13.9.2
rpds-py                        0.10.6
rsa                            4.9
safetensors                    0.4.5
scipy                          1.14.1
Send2Trash                     1.8.2
setuptools                     75.1.0
shellingham                    1.5.4
sip                            6.7.12
six                            1.16.0
sniffio                        1.3.0
soupsieve                      2.5
stack-data                     0.2.0
sympy                          1.13.1
tabulate                       0.9.0
tb-nightly                     2.18.0a20240925
tensorboard-data-server        0.7.2
tensorflow-io-gcs-filesystem   0.37.1
termcolor                      2.5.0
terminado                      0.17.1
tf_nightly                     2.19.0.dev20241001
tinycss2                       1.2.1
torch                          2.5.0
torch-xla                      2.5.0
torch_xla_cuda_plugin          2.5.0
torchmetrics                   1.4.3
torchvision                    0.20.0
tornado                        6.4.1
tqdm                           4.66.5
traitlets                      5.14.3
triton                         3.1.0
typer                          0.12.5
typing_extensions              4.12.2
uritemplate                    3.0.1
urllib3                        2.2.3
wcwidth                        0.2.5
webencodings                   0.5.1
websocket-client               1.8.0
Werkzeug                       3.0.4
wheel                          0.44.0
widgetsnbextension             4.0.10
wrapt                          1.16.0
yacs                           0.1.8
yarl                           1.15.4
```

i use conda and wsl2

**Comment by shubhamgupto** [comment]
I could not reproduce this but I instead solved my issue by replacing batchnorm2d with identity and conv layers, it works. Feel free to close it but I feel the module should be invariant to the system setup.
