### ISSUE TITLE
Error while running Quantize example.py script for llama

### ISSUE THREAD

**Issue by Arya-Hari** [google-ai-edge/ai-edge-torch#322]
### Description of the bug:

I tried running the example.py script given for quantization example, but for Llama. I made the following changes in the code - 
`from ai_edge_torch.generative.examples.llama import llama` instead of `from ai_edge_torch.generative.examples.gemma import gemma1` and 
`config = llama.get_fake_model_config()`
 `model = llama.Llama(config)`
instead of 
`config = gemma1.get_fake_model_config()`
 `model = gemma1.Gemma(config)`

It gives me this error - 
`Traceback (most recent call last):
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2713, in inline_call_
    sub_locals, closure_cells = func.bind_args(parent, args, kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 203, in bind_args
    bound = inspect.signature(fake_func).bind(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3195, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3110, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'kv_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ai-edge-torch/ai_edge_torch/generative/quantize/example.py", line 44, in <module>
    main()
  File "/home/ai-edge-torch/ai_edge_torch/generative/quantize/example.py", line 37, in main
    edge_model = ai_edge_torch.convert(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 254, in convert
    return Converter().convert(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 169, in convert
    return conversion.convert_signatures(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai-edge-torch/ai_edge_torch/_convert/conversion.py", line 131, in convert_signatures
    exported_programs: torch.export.ExportedProgram = [
                                                      ^
  File "/home/ai-edge-torch/ai_edge_torch/_convert/conversion.py", line 132, in <listcomp>
    export(sig.module, sig.flat_args, dynamic_shapes=sig.dynamic_shapes)
  File "/home/ai-edge-torch/ai_edge_torch/_convert/conversion.py", line 119, in export
    exported_program = torch.export.export(*args, **kwargs, strict=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/export/__init__.py", line 174, in export
    return _export(
           ^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/export/_trace.py", line 945, in wrapper
    raise e
  File "/home/venv/lib/python3.11/site-packages/torch/export/_trace.py", line 928, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/export/exported_program.py", line 89, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/export/_trace.py", line 1455, in _export
    aten_export_artifact = export_func(
                           ^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/export/_trace.py", line 1060, in _strict_export
    gm_torch_level = _export_to_torch_ir(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/export/_trace.py", line 512, in _export_to_torch_ir
    gm_torch_level, _ = torch._dynamo.export(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 1379, in inner
    result_traced = opt_f(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2451, in run
    super().run()
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/nn_module.py", line 437, in call_function
    return tx.inline_user_function_return(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 344, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2782, in inline_call_
    tracer.run()
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 499, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1500, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 749, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2666, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2716, in inline_call_
    raise ArgsMismatchError(  # noqa: B904
torch._dynamo.exc.ArgsMismatchError: missing a required argument: 'kv_cache'.
  func = 'forward' /home/ai-edge-torch/ai_edge_torch/generative/utilities/model_builder.py:89, args = [<class 'ai_edge_torch.generative.examples.llama.llama.Llama'>, <class 'torch.Tensor'>, <class 'torch.Tensor'>], kwargs = {}

from user code:
   File "/home/venv/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 38, in inner
    return fn(*args, **kwargs)
  File "/home/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information`

### Actual vs expected behavior:

I just tried to follow the example script for quantization and ideally at the end the tflite script should have been created. But it gives me this error.

### Any other information you'd like to share?

I don't know if it changes anything, but I'm running the script on WSL.

**Comment by haozha111** [comment]
the `example.py` didn't use the latest external kv cache, i will make a PR to fix it.

**Comment by haozha111** [comment]
can you check if https://github.com/google-ai-edge/ai-edge-torch/commit/61800adf42c4bc3782827eab47267f9f1f3a198c fix your issue?

**Comment by Arya-Hari** [comment]
Okay I will try it out! Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @Arya-Hari 
I apologize for the delayed response, I have tried from my end and now `example.py` script is working as expected without `TypeError: missing a required argument: 'kv_cache'`

I have created separate file named as `convert_fake_llama_quantized.py` for llama model instead of using `example.py` file and it's working as expected also we updated our `example.py` script [here](https://github.com/google-ai-edge/ai-edge-torch/blob/main/ai_edge_torch/generative/quantize/example.py) with external kv cache

```
(my_venv) (base) gaikwadrahul@gaikwadrahul-n1-standard-1-gpu-t4x1-tflite-ubuntu-22:~/edge_conversion_issue_#636$ python convert_fake_llama_quantized.py
2025-05-16 13:09:47.136618: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:354: UserWarning: Device capability of jax unspecified, assuming `cpu` and `cuda`. Please specify it via the `devices` argument of `register_backend`.
  warnings.warn(
WARNING:2025-05-16 13:09:51,079:jax._src.xla_bridge:909: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
QuantConfig(pt2e_quantizer=None, generative_recipe=GenerativeQuantRecipe(
  Default: (a:FP32, w:INT8, DYNAMIC_RANGE, MIN_MAX, CHANNELWISE, 0)
  Embedding: None
  Attention: None
  Feedforward: None
), _quantizer_mode=<_QuantizerMode.AI_EDGE_QUANTIZER: 4>)

Starting model conversion with quantization...
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/export/_unlift.py:75: UserWarning: Attempted to insert a get_attr Node with no underlying reference in the owning GraphModule! Call GraphModule.add_submodule to add the necessary submodule, GraphModule.add_parameter to add the necessary Parameter, or nn.Module.register_buffer to add the necessary buffer
  getattr_node = gm.graph.get_attr(lifted_node)
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/fx/graph.py:1801: UserWarning: Node mask_cache target mask_cache mask_cache of  does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/export/_unlift.py:75: UserWarning: Attempted to insert a get_attr Node with no underlying reference in the owning GraphModule! Call GraphModule.add_submodule to add the necessary submodule, GraphModule.add_parameter to add the necessary Parameter, or nn.Module.register_buffer to add the necessary buffer
  getattr_node = gm.graph.get_attr(lifted_node)
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/fx/graph.py:1801: UserWarning: Node mask_cache target mask_cache mask_cache of  does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/export/_unlift.py:75: UserWarning: Attempted to insert a get_attr Node with no underlying reference in the owning GraphModule! Call GraphModule.add_submodule to add the necessary submodule, GraphModule.add_parameter to add the necessary Parameter, or nn.Module.register_buffer to add the necessary buffer
  getattr_node = gm.graph.get_attr(lifted_node)
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/fx/graph.py:1801: UserWarning: Node mask_cache target mask_cache mask_cache of  does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/export/_unlift.py:75: UserWarning: Attempted to insert a get_attr Node with no underlying reference in the owning GraphModule! Call GraphModule.add_submodule to add the necessary submodule, GraphModule.add_parameter to add the necessary Parameter, or nn.Module.register_buffer to add the necessary buffer
  getattr_node = gm.graph.get_attr(lifted_node)
/home/gaikwadrahul/edge_conversion_issue_#636/my_venv/lib/python3.12/site-packages/torch/fx/graph.py:1801: UserWarning: Node mask_cache target mask_cache mask_cache of  does not reference an nn.Module, nn.Parameter, or buffer, which is what 'get_attr' Nodes typically target
  warnings.warn(
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1747401000.117235    6334 gpu_device.cc:2018] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13775 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
W0000 00:00:1747401001.856126    6334 tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
W0000 00:00:1747401001.856175    6334 tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2025-05-16 13:10:01.857196: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tmpwzdcfbsh
2025-05-16 13:10:01.858073: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2025-05-16 13:10:01.858094: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: /tmp/tmpwzdcfbsh
I0000 00:00:1747401001.864478    6334 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
2025-05-16 13:10:01.865463: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2025-05-16 13:10:01.986233: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: /tmp/tmpwzdcfbsh
2025-05-16 13:10:01.997738: I tensorflow/cc/saved_model/loader.cc:471] SavedModel load for tags { serve }; Status: success: OK. Took 140548 microseconds.
2025-05-16 13:10:02.014348: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2025-05-16 13:10:07.259323: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:4096] Estimated count of arithmetic ops: 487.863 M  ops, equivalently 243.932 M  MACs
Conversion completed.
Exporting TFLite model to /tmp/llama_fake_quantized.tflite...
Export completed successfully!

(my_venv) (base) gaikwadrahul@gaikwadrahul-n1-standard-1-gpu-t4x1-tflite-ubuntu-22:~/edge_conversion_issue_#636$ ls -lh /tmp/llama_fake_quantized.tflite
-rw-rw-r-- 1 gaikwadrahul gaikwadrahul 26M May 16 13:10 /tmp/llama_fake_quantized.tflite
(my_venv) (base) gaikwadrahul@gaikwadrahul-n1-standard-1-gpu-t4x1-tflite-ubuntu-22:~/edge_conversion_issue_#636$ 
```

If your issue is now resolved, please feel free to close this issue. For any further assistance or additional questions, please create a new issue and we will be happy to help. Thank you for your cooperation and understanding.
