### ISSUE TITLE
Llama-3.2-1B `verify.py` error

### ISSUE THREAD

**Issue by mikel-brostrom** [google-ai-edge/ai-edge-torch#410]
### Description of the bug:

Do I need a specific version of the transformers package?

```bash
$ python3 ai_edge_torch/generative/examples/llama/verify.py
2024-12-10 10:48:42.168833: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-10 10:48:42.213564: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I1210 10:48:48.800797 140093764445312 verify_llama32_1b.py:58] Loading the original model from: meta-llama/Llama-3.2-1B-Instruct
I1210 10:49:51.307868 140093764445312 verify_llama32_1b.py:66] Building the reauthored model from: /root/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/9213176726f574b556790deb65791e0c5aa438b6
I1210 10:50:01.263940 140093764445312 verify_llama32_1b.py:69] Loading the tokenizer from: meta-llama/Llama-3.2-1B-Instruct
I1210 10:50:03.017452 140093764445312 verifier.py:303] Verifying the reauthored model with input IDs: [1, 2, 3, 4]
I1210 10:50:03.017939 140093764445312 verifier.py:210] Forwarding the original model...
I1210 10:50:14.915034 140093764445312 verifier.py:213] logits_original: tensor([ 9.2015,  9.3586, 14.1001,  ..., -1.4927, -1.4921, -1.4925],
       grad_fn=<SliceBackward0>)
I1210 10:50:14.917109 140093764445312 verifier.py:215] Forwarding the reauthored model...
I1210 10:50:25.047351 140093764445312 verifier.py:218] logits_reauthored: tensor([ 9.2015,  9.3586, 14.1001,  ..., -1.4927, -1.4921, -1.4925])
I1210 10:50:25.069791 140093764445312 verifier.py:314] *** PASSED *** verify with input IDs: [1, 2, 3, 4]
I1210 10:50:25.069975 140093764445312 verifier.py:317] Verifying the reauthored model with prompts: What is the meaning of life?
I1210 10:50:25.071385 140093764445312 verifier.py:251] Generating answer with the original model...
Traceback (most recent call last):
  File "/builds/cevt/data/sandbox/zeekr-places-ml/verify_llama32_1b.py", line 88, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/builds/cevt/data/sandbox/zeekr-places-ml/verify_llama32_1b.py", line 75, in main
    verifier.verify_reauthored_model(
  File "/usr/local/lib/python3.10/dist-packages/ai_edge_torch/generative/utilities/verifier.py", line 319, in verify_reauthored_model
    verify_model_with_prompts(
  File "/usr/local/lib/python3.10/dist-packages/ai_edge_torch/generative/utilities/verifier.py", line 252, in verify_model_with_prompts
    outputs_original = original_model.generate(prompt_tokens, max_new_tokens)
  File "/usr/local/lib/python3.10/dist-packages/ai_edge_torch/generative/utilities/transformers_verifier.py", line 41, in generate
    export_config = transformers.ExportConfig(max_new_tokens=max_new_tokens)
  File "/transformers/src/transformers/utils/import_utils.py", line 1786, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute ExportConfig
```

**Comment by haozha111** [comment]
This seems to relate with a recent change. @talumbau fyi

**Comment by talumbau** [comment]
Hi thanks for the bug report! I think this was fixed via https://github.com/google-ai-edge/ai-edge-torch/pull/414/ Can you pull the latest changes in the main branch and try again? Thanks!

**Comment by pkgoogle** [comment]
@mikel-brostrom tagging for attention, let us know if the above fixes it for you. Thanks.

**Comment by mikel-brostrom** [comment]
Seems to work 😄 

```bash
$ python3 ai_edge_torch/generative/examples/llama/verify.py
2024-12-13 07:54:49.335408: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-13 07:54:49.350553: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734076489.369165    1670 cuda_dnn.cc:8501] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734076489.374542    1670 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-13 07:54:49.392594: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-13 07:54:57.753663: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
I1213 07:54:57.753[847](https://gitlab.com/cevt/data/sandbox/zeekr-places-ml/-/jobs/8632362319#L847) 140104205644928 verify_llama32_1b.py:58] Loading the original model from: meta-llama/Llama-3.2-1B-Instruct
I1213 07:55:59.248368 140104205644928 verify_llama32_1b.py:66] Building the reauthored model from: /root/.cache/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/9213176726f574b556790deb65791e0c5aa438b6
I1213 07:56:08.819326 140104205644928 verify_llama32_1b.py:69] Loading the tokenizer from: meta-llama/Llama-3.2-1B-Instruct
I1213 07:56:10.430176 140104205644928 verifier.py:303] Verifying the reauthored model with input IDs: [1, 2, 3, 4]
I1213 07:56:10.430641 140104205644928 verifier.py:210] Forwarding the original model...
I1213 07:56:21.847291 140104205644928 verifier.py:213] logits_original: tensor([ 9.2015,  9.3586, 14.1001,  ..., -1.4927, -1.4921, -1.4925],
       grad_fn=<SliceBackward0>)
I1213 07:56:21.[849](https://gitlab.com/cevt/data/sandbox/zeekr-places-ml/-/jobs/8632362319#L849)449 140104205644928 verifier.py:215] Forwarding the reauthored model...
I1213 07:56:31.751462 140104205644928 verifier.py:218] logits_reauthored: tensor([ 9.2015,  9.3586, 14.1001,  ..., -1.4927, -1.4921, -1.4925])
I1213 07:56:31.776573 140104205644928 verifier.py:314] *** PASSED *** verify with input IDs: [1, 2, 3, 4]
I1213 07:56:31.776757 140104205644928 verifier.py:317] Verifying the reauthored model with prompts: What is the meaning of life?
I1213 07:56:31.778395 140104205644928 verifier.py:251] Generating answer with the original model...
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
I1213 07:56:37.842034 140104205644928 verifier.py:254] outputs_from_original_model: [[<|begin_of_text|>What is the meaning of life? A question that has puzzled philosophers, theologians, scientists, and everyday people for centuries. The answer, of course, is subjective and can vary greatly]]
I1213 07:56:37.842201 140104205644928 verifier.py:256] Generating answer with the reauthored model...
I1213 07:56:45.374063 140104205644928 verifier.py:259] outputs from reauthored model: [[<|begin_of_text|>What is the meaning of life? A question that has puzzled philosophers, theologians, scientists, and everyday people for centuries. The answer, of course, is subjective and can vary greatly]]
I1213 07:56:45.374240 140104205644928 verifier.py:328] *** PASSED *** verify with prompts: What is the meaning of life?
I1213 07:56:45.374299 140104205644928 verifier.py:331] *** PASSED *** verify_reauthored_model
```
